
;Play 1.5k frequency for .3 seconds
PLAYHIGHSOUND: LDI R19, 112
HIGHDELAY1: LDI R20, 4
HIGHDELAY2: SBI PORTC, 6
RCALL HIGHFREQ
NOP
NOP
CBI PORTC, 6
RCALL HIGHFREQ
DEC R20
BRNE HIGHDELAY2
DEC R19
BRNE HIGHDELAY1
RET

;Delay between switches to speaker port bit
HIGHFREQ: LDI R17, 116
HIGHFREQ1: LDI R18, 6
NOP
NOP
HIGHFREQ2: DEC R18
BRNE HIGHFREQ2
DEC R17
BRNE HIGHFREQ1
RET

;Play 1k frequency for .3 seconds
PLAYLOWSOUND: LDI R19, 23
LOWDELAY1: LDI R20, 14
LOWDELAY2: SBI PORTC, 6
RCALL LOWFREQ
NOP
NOP
CBI PORTC, 6
RCALL LOWFREQ
DEC R20
BRNE LOWDELAY2
DEC R19
BRNE LOWDELAY1
RET

;Delay between switches to speaker port bit
LOWFREQ: LDI R17, 200
LOWFREQ1: LDI R18, 5
NOP
NOP
LOWFREQ2: DEC R18
BRNE LOWFREQ2
DEC R17
BRNE LOWFREQ1
RET

